services:
  builder:
    image: ubuntu:22.04
    privileged: true
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    #
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./rootfs:/rootfs:ro
      - ./input:/input:ro
      - ./output:/output:rw
    #
    env_file: .env
    environment:
      DEBIAN_FRONTEND: noninteractive
      # UBUNTU_MIRROR: http://my-cache.local:3142/ubuntu-ports
      ROM_NAME: ubuntu-22.04-xfce
    #
    tmpfs:
      - /build:exec,size=4g
      - /chroot:exec,size=4g
