Section "InputClass"
    Identifier "evdev touchscreen catchall"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Driver "evdev"
    Option "Calibration" "0 1199 0 1919"
    Option "TransformationMatrix" "0 1 0 -1 0 1 0 0 1"
EndSection
