Section "InputClass"
	Identifier "evdev touchscreen catchall"
	MatchIsTouchscreen "on"
	MatchDevicePath "/dev/input/event*"
	Driver "evdev"
	Option "InvertY" "true"
	Option "InvertX" "true"
	Option "Calibration" "0 1199 0 1919"
EndSection
